version: "3.3"

services:
  postgres:
    image: postgres:13.1-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./scripts/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    ports:
      - 5432:5432
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: my-messenger
      POSTGRES_PASSWORD: 123
